### ISSUE TITLE
Not working on Bukkit 1.2.4 #2126

### ISSUE THREAD

**Issue by moritzhoewer** [iConomy/Core#176]
When I start Bukkit 1.2.4  Build #2126 (Recomended) I get this output:
No other Mods were running.

_[INFORMATION] [iConomy] Enabling iConomy v6.0.8b
[INFO] [iConomy] Default setup file written: Config.yml
[INFO] [iConomy] Default setup file written: Template.yml
[SEVERE] Error occurred while enabling iConomy v6.0.8b (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/util/config/Configuration
        at com.iCo6.iConomy.onEnable(iConomy.java:114)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:374)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:361)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.ClassNotFoundException: org.bukkit.util.config.Configuration
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 11 more_

**Comment by Acrobot** [comment]
You are not using the latest version of iConomy.

**Comment by nijikokun** [comment]
Closing due to incorrect version with latest build of bukkit.

**Comment by moritzhoewer** [comment]
Thanks
